# Site settings
title: Console Breadcrumbs
email: oldcar@inbox.lv
description: "Yet another github user page about programming, bash scripting, git usage and other bits and pieces"
baseurl: ""
url: "https://kubilisr.github.io"
twitter_username: kubilisr
github_username:  wolf3d
founded: 2016    

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title

gems: [jekyll-gist]
